/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/country/classic-country.js
   50 albume esențiale de Country Clasic & Folk
═══════════════════════════════════════════════════════════════ */

window.classicCountryData = {
    gen: 'country',
    subgen: 'classic-country',
    label: 'Country Clasic',
    albume: [
        { artist: 'Johnny Cash',           album: 'At Folsom Prison',                    an: 1968 },
        { artist: 'Johnny Cash',           album: 'American Recordings',                 an: 1994 },
        { artist: 'Johnny Cash',           album: 'American IV: The Man Comes Around',   an: 2002 },
        { artist: 'Dolly Parton',          album: 'Jolene',                              an: 1974 },
        { artist: 'Dolly Parton',          album: 'Coat of Many Colors',                 an: 1971 },
        { artist: 'Dolly Parton',          album: 'I Will Always Love You',              an: 1974 },
        { artist: 'Willie Nelson',         album: 'Red Headed Stranger',                 an: 1975 },
        { artist: 'Willie Nelson',         album: 'Stardust',                            an: 1978 },
        { artist: 'Willie Nelson',         album: 'Always on My Mind',                   an: 1982 },
        { artist: 'Waylon Jennings',       album: 'Dreaming My Dreams',                  an: 1975 },
        { artist: 'Waylon Jennings',       album: 'Are You Ready for the Country',       an: 1976 },
        { artist: 'Merle Haggard',         album: 'Mama Tried',                          an: 1968 },
        { artist: 'Merle Haggard',         album: 'Okie from Muskogee',                  an: 1969 },
        { artist: 'Hank Williams',         album: '40 Greatest Hits',                    an: 1978 },
        { artist: 'Patsy Cline',           album: 'Showcase',                            an: 1961 },
        { artist: 'Patsy Cline',           album: 'Sentimentally Yours',                 an: 1962 },
        { artist: 'Loretta Lynn',          album: 'Coal Miner\'s Daughter',              an: 1971 },
        { artist: 'Loretta Lynn',          album: 'Van Lear Rose',                       an: 2004 },
        { artist: 'George Jones',          album: 'He Stopped Loving Her Today',         an: 1980 },
        { artist: 'Kenny Rogers',          album: 'The Gambler',                         an: 1978 },
        { artist: 'Glen Campbell',         album: 'Wichita Lineman',                     an: 1968 },
        { artist: 'Glen Campbell',         album: 'Galveston',                           an: 1969 },
        { artist: 'Bob Dylan',             album: 'Nashville Skyline',                   an: 1969 },
        { artist: 'Bob Dylan',             album: 'Blood on the Tracks',                 an: 1975 },
        { artist: 'James Taylor',          album: 'Sweet Baby James',                    an: 1970 },
        { artist: 'James Taylor',          album: 'Mud Slide Slim',                      an: 1971 },
        { artist: 'Simon & Garfunkel',     album: 'Bridge Over Troubled Water',          an: 1970 },
        { artist: 'Gram Parsons',          album: 'GP',                                  an: 1973 },
        { artist: 'Gram Parsons',          album: 'Grievous Angel',                      an: 1974 },
        { artist: 'The Eagles',            album: 'Desperado',                           an: 1973 },
        { artist: 'The Eagles',            album: 'Hotel California',                    an: 1976 },
        { artist: 'Townes Van Zandt',      album: 'Our Mother the Mountain',             an: 1969 },
        { artist: 'Townes Van Zandt',      album: 'Live at the Old Quarter',             an: 1977 },
        { artist: 'Guy Clark',             album: 'Old No. 1',                           an: 1975 },
        { artist: 'Kris Kristofferson',    album: 'Kristofferson',                       an: 1970 },
        { artist: 'John Denver',           album: 'Rocky Mountain High',                 an: 1972 },
        { artist: 'John Denver',           album: 'Back Home Again',                     an: 1974 },
        { artist: 'Linda Ronstadt',        album: 'Heart Like a Wheel',                  an: 1974 },
        { artist: 'Linda Ronstadt',        album: 'Simple Dreams',                       an: 1977 },
        { artist: 'Crystal Gayle',         album: 'We Must Believe in Magic',            an: 1977 },
        { artist: 'Emmylou Harris',        album: 'Pieces of the Sky',                   an: 1975 },
        { artist: 'Emmylou Harris',        album: 'Elite Hotel',                         an: 1975 },
        { artist: 'Don Williams',          album: 'Expressions',                         an: 1978 },
        { artist: 'Dwight Yoakam',         album: 'Guitars, Cadillacs, Etc., Etc.',      an: 1986 },
        { artist: 'Dwight Yoakam',         album: 'Buenos Noches from a Lonely Room',    an: 1988 },
        { artist: 'Alan Jackson',          album: 'Don\'t Rock the Jukebox',             an: 1991 },
        { artist: 'Garth Brooks',          album: 'No Fences',                           an: 1990 },
        { artist: 'Garth Brooks',          album: 'Ropin\' the Wind',                    an: 1991 },
        { artist: 'Vince Gill',            album: 'When I Call Your Name',               an: 1990 },
        { artist: 'Trisha Yearwood',       album: 'Trisha Yearwood',                     an: 1991 },
    ]
};
