/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/country/contemporary.js
   50 albume esențiale de Country Contemporan (1990-2024)
═══════════════════════════════════════════════════════════════ */

window.contemporaryCountryData = {
    gen: 'country',
    subgen: 'contemporary',
    label: 'Country Contemporan',
    albume: [
        { artist: 'Kacey Musgraves',       album: 'Golden Hour',                         an: 2018 },
        { artist: 'Kacey Musgraves',       album: 'Same Trailer Different Park',         an: 2013 },
        { artist: 'Kacey Musgraves',       album: 'Pageant Material',                    an: 2015 },
        { artist: 'Chris Stapleton',       album: 'Traveller',                           an: 2015 },
        { artist: 'Chris Stapleton',       album: 'From a Room: Volume 1',               an: 2017 },
        { artist: 'Chris Stapleton',       album: 'Starting Over',                       an: 2020 },
        { artist: 'Sturgill Simpson',      album: 'Metamodern Sounds in Country Music',  an: 2014 },
        { artist: 'Sturgill Simpson',      album: 'A Sailor\'s Guide to Earth',          an: 2016 },
        { artist: 'Brandi Carlile',        album: 'By the Way, I Forgive You',           an: 2018 },
        { artist: 'Brandi Carlile',        album: 'In These Silent Days',                an: 2021 },
        { artist: 'Maren Morris',          album: 'Hero',                                an: 2016 },
        { artist: 'Maren Morris',          album: 'Girl',                                an: 2019 },
        { artist: 'Miranda Lambert',       album: 'Kerosene',                            an: 2005 },
        { artist: 'Miranda Lambert',       album: 'Revolution',                          an: 2009 },
        { artist: 'Miranda Lambert',       album: 'Platinum',                            an: 2014 },
        { artist: 'Miranda Lambert',       album: 'The Weight of These Wings',           an: 2016 },
        { artist: 'Carrie Underwood',      album: 'Some Hearts',                         an: 2005 },
        { artist: 'Carrie Underwood',      album: 'Carnival Ride',                       an: 2007 },
        { artist: 'Carrie Underwood',      album: 'Blown Away',                          an: 2012 },
        { artist: 'Dierks Bentley',        album: 'Up on the Ridge',                     an: 2010 },
        { artist: 'Eric Church',           album: 'Chief',                               an: 2011 },
        { artist: 'Eric Church',           album: 'Mr. Misunderstood',                   an: 2015 },
        { artist: 'Eric Church',           album: 'Heart & Soul',                        an: 2021 },
        { artist: 'Zac Brown Band',        album: 'You Get What You Give',               an: 2010 },
        { artist: 'Zac Brown Band',        album: 'Jekyll + Hyde',                       an: 2015 },
        { artist: 'Jason Isbell',          album: 'Southeastern',                        an: 2013 },
        { artist: 'Jason Isbell',          album: 'Something More Than Free',            an: 2015 },
        { artist: 'Jason Isbell',          album: 'The Nashville Sound',                 an: 2017 },
        { artist: 'Tyler Childers',        album: 'Purgatory',                           an: 2017 },
        { artist: 'Tyler Childers',        album: 'Country Squire',                      an: 2019 },
        { artist: 'Lyle Lovett',           album: 'Joshua Judges Ruth',                  an: 1992 },
        { artist: 'Lyle Lovett',           album: 'The Road to Ensenada',                an: 1996 },
        { artist: 'Emmylou Harris',        album: 'Wrecking Ball',                       an: 1995 },
        { artist: 'Emmylou Harris',        album: 'Red Dirt Girl',                       an: 2000 },
        { artist: 'Alison Krauss',         album: 'Forget About It',                     an: 1999 },
        { artist: 'Alison Krauss',         album: 'Raising Sand',                        an: 2007 },
        { artist: 'Alison Krauss',         album: 'Windy City',                          an: 2017 },
        { artist: 'Brad Paisley',          album: 'Mud on the Tires',                    an: 2003 },
        { artist: 'Brad Paisley',          album: 'Time Well Wasted',                    an: 2005 },
        { artist: 'Kenny Chesney',         album: 'No Shoes No Shirt No Problems',       an: 2002 },
        { artist: 'Tim McGraw',            album: 'Set This Circus Down',                an: 2001 },
        { artist: 'Tim McGraw',            album: 'Live Like You Were Dying',            an: 2004 },
        { artist: 'Luke Combs',            album: 'This One\'s for You',                 an: 2017 },
        { artist: 'Luke Combs',            album: 'What You See Is What You Get',        an: 2019 },
        { artist: 'Morgan Wallen',         album: 'Dangerous: The Double Album',         an: 2021 },
        { artist: 'Cody Johnson',          album: '\'Til You Can\'t',                    an: 2021 },
        { artist: 'Zach Bryan',            album: 'American Heartbreak',                 an: 2022 },
        { artist: 'Zach Bryan',            album: 'Zach Bryan',                          an: 2023 },
        { artist: 'Lainey Wilson',         album: 'Bell Bottom Country',                 an: 2022 },
        { artist: 'Sierra Ferrell',        album: 'Long Time Coming',                    an: 2021 },
    ]
};
