/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/rock/alternative.js
   50 albume esențiale de Alternative Rock
═══════════════════════════════════════════════════════════════ */

window.alternativeData = {
    gen: 'rock',
    subgen: 'alternative',
    label: 'Alternative Rock',
    albume: [
        { artist: 'Nirvana',               album: 'Nevermind',                           an: 1991 },
        { artist: 'Nirvana',               album: 'In Utero',                            an: 1993 },
        { artist: 'Radiohead',             album: 'OK Computer',                         an: 1997 },
        { artist: 'Radiohead',             album: 'The Bends',                           an: 1995 },
        { artist: 'Radiohead',             album: 'Kid A',                               an: 2000 },
        { artist: 'Pearl Jam',             album: 'Ten',                                 an: 1991 },
        { artist: 'Pearl Jam',             album: 'Vs.',                                 an: 1993 },
        { artist: 'Soundgarden',           album: 'Superunknown',                        an: 1994 },
        { artist: 'Soundgarden',           album: 'Badmotorfinger',                      an: 1991 },
        { artist: 'Alice in Chains',       album: 'Dirt',                                an: 1992 },
        { artist: 'Alice in Chains',       album: 'Facelift',                            an: 1990 },
        { artist: 'Stone Temple Pilots',   album: 'Core',                                an: 1992 },
        { artist: 'R.E.M.',                album: 'Automatic for the People',            an: 1992 },
        { artist: 'R.E.M.',                album: 'Out of Time',                         an: 1991 },
        { artist: 'The Smashing Pumpkins', album: 'Siamese Dream',                       an: 1993 },
        { artist: 'The Smashing Pumpkins', album: 'Mellon Collie and the Infinite Sadness', an: 1995 },
        { artist: 'Pixies',                album: 'Doolittle',                           an: 1989 },
        { artist: 'Pixies',                album: 'Surfer Rosa',                         an: 1988 },
        { artist: 'The Cure',              album: 'Disintegration',                      an: 1989 },
        { artist: 'The Cure',              album: 'Pornography',                         an: 1982 },
        { artist: 'Depeche Mode',          album: 'Violator',                            an: 1990 },
        { artist: 'Depeche Mode',          album: 'Songs of Faith and Devotion',         an: 1993 },
        { artist: 'Jane\'s Addiction',      album: 'Nothing\'s Shocking',                an: 1988 },
        { artist: 'Sonic Youth',           album: 'Daydream Nation',                     an: 1988 },
        { artist: 'My Bloody Valentine',   album: 'Loveless',                            an: 1991 },
        { artist: 'The Replacements',      album: 'Let It Be',                           an: 1984 },
        { artist: 'Dinosaur Jr.',          album: 'You\'re Living All Over Me',          an: 1987 },
        { artist: 'Pavement',              album: 'Slanted and Enchanted',               an: 1992 },
        { artist: 'Beck',                  album: 'Odelay',                              an: 1996 },
        { artist: 'Beck',                  album: 'Sea Change',                          an: 2002 },
        { artist: 'Weezer',                album: 'Weezer (Blue Album)',                 an: 1994 },
        { artist: 'The Cranberries',       album: 'Everybody Else Is Doing It',          an: 1993 },
        { artist: 'Blur',                  album: 'Parklife',                            an: 1994 },
        { artist: 'Blur',                  album: '13',                                  an: 1999 },
        { artist: 'Oasis',                 album: '(What\'s the Story) Morning Glory?',  an: 1995 },
        { artist: 'Oasis',                 album: 'Definitely Maybe',                    an: 1994 },
        { artist: 'Pulp',                  album: 'Different Class',                     an: 1995 },
        { artist: 'Suede',                 album: 'Coming Up',                           an: 1996 },
        { artist: 'The Verve',             album: 'Urban Hymns',                         an: 1997 },
        { artist: 'Placebo',               album: 'Without You I\'m Nothing',            an: 1998 },
        { artist: 'Nine Inch Nails',       album: 'The Downward Spiral',                 an: 1994 },
        { artist: 'Marilyn Manson',        album: 'Antichrist Superstar',                an: 1996 },
        { artist: 'Tool',                  album: 'Ænima',                               an: 1996 },
        { artist: 'Tool',                  album: 'Lateralus',                           an: 2001 },
        { artist: 'A Perfect Circle',      album: 'Mer de Noms',                         an: 2000 },
        { artist: 'Foo Fighters',          album: 'The Colour and the Shape',            an: 1997 },
        { artist: 'Foo Fighters',          album: 'There Is Nothing Left to Lose',       an: 1999 },
        { artist: 'Green Day',             album: 'Dookie',                              an: 1994 },
        { artist: 'The White Stripes',     album: 'Elephant',                            an: 2003 },
        { artist: 'The Strokes',           album: 'Is This It',                          an: 2001 },
    ]
};
