/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/rock/classic-rock.js
   50 albume esențiale de Classic Rock
   Surse: Rolling Stone 500, AllMusic Essentials, Rate Your Music
═══════════════════════════════════════════════════════════════ */

window.classicRockData = {
    gen: 'rock',
    subgen: 'classic-rock',
    label: 'Classic Rock',
    albume: [
        { artist: 'The Beatles',           album: 'Abbey Road',                          an: 1969 },
        { artist: 'The Beatles',           album: 'Sgt. Pepper\'s Lonely Hearts Club Band', an: 1967 },
        { artist: 'The Beatles',           album: 'Revolver',                            an: 1966 },
        { artist: 'The Rolling Stones',    album: 'Exile on Main St.',                   an: 1972 },
        { artist: 'Led Zeppelin',          album: 'Led Zeppelin IV',                     an: 1971 },
        { artist: 'Led Zeppelin',          album: 'Physical Graffiti',                   an: 1975 },
        { artist: 'Led Zeppelin',          album: 'Led Zeppelin II',                     an: 1969 },
        { artist: 'Pink Floyd',            album: 'The Dark Side of the Moon',           an: 1973 },
        { artist: 'Pink Floyd',            album: 'Wish You Were Here',                  an: 1975 },
        { artist: 'Pink Floyd',            album: 'The Wall',                            an: 1979 },
        { artist: 'The Who',               album: 'Who\'s Next',                         an: 1971 },
        { artist: 'The Who',               album: 'Tommy',                               an: 1969 },
        { artist: 'Bob Dylan',             album: 'Highway 61 Revisited',                an: 1965 },
        { artist: 'Bob Dylan',             album: 'Blonde on Blonde',                    an: 1966 },
        { artist: 'Bob Dylan',             album: 'Blood on the Tracks',                 an: 1975 },
        { artist: 'Jimi Hendrix',          album: 'Are You Experienced',                 an: 1967 },
        { artist: 'Jimi Hendrix',          album: 'Electric Ladyland',                   an: 1968 },
        { artist: 'The Doors',             album: 'The Doors',                           an: 1967 },
        { artist: 'Creedence Clearwater Revival', album: 'Cosmo\'s Factory',             an: 1970 },
        { artist: 'Fleetwood Mac',         album: 'Rumours',                             an: 1977 },
        { artist: 'Eagles',                album: 'Hotel California',                    an: 1976 },
        { artist: 'The Beach Boys',        album: 'Pet Sounds',                          an: 1966 },
        { artist: 'Bruce Springsteen',     album: 'Born to Run',                         an: 1975 },
        { artist: 'Bruce Springsteen',     album: 'Darkness on the Edge of Town',        an: 1978 },
        { artist: 'Neil Young',            album: 'After the Gold Rush',                 an: 1970 },
        { artist: 'Neil Young',            album: 'Harvest',                             an: 1972 },
        { artist: 'Simon & Garfunkel',     album: 'Bridge Over Troubled Water',          an: 1970 },
        { artist: 'Crosby Stills Nash & Young', album: 'Déjà Vu',                       an: 1970 },
        { artist: 'Tom Petty',             album: 'Damn the Torpedoes',                  an: 1979 },
        { artist: 'Elton John',            album: 'Goodbye Yellow Brick Road',           an: 1973 },
        { artist: 'David Bowie',           album: 'The Rise and Fall of Ziggy Stardust', an: 1972 },
        { artist: 'David Bowie',           album: 'Station to Station',                  an: 1976 },
        { artist: 'Santana',               album: 'Abraxas',                             an: 1970 },
        { artist: 'Janis Joplin',          album: 'Pearl',                               an: 1971 },
        { artist: 'Credence Clearwater Revival', album: 'Green River',                   an: 1969 },
        { artist: 'The Kinks',             album: 'The Kinks Are the Village Green Preservation Society', an: 1968 },
        { artist: 'Van Morrison',          album: 'Astral Weeks',                        an: 1968 },
        { artist: 'Van Morrison',          album: 'Moondance',                           an: 1970 },
        { artist: 'Joni Mitchell',         album: 'Blue',                                an: 1971 },
        { artist: 'Joni Mitchell',         album: 'Court and Spark',                     an: 1974 },
        { artist: 'The Byrds',             album: 'Mr. Tambourine Man',                  an: 1965 },
        { artist: 'Jefferson Airplane',    album: 'Surrealistic Pillow',                 an: 1967 },
        { artist: 'Cream',                 album: 'Disraeli Gears',                      an: 1967 },
        { artist: 'Cream',                 album: 'Wheels of Fire',                      an: 1968 },
        { artist: 'Grateful Dead',         album: 'American Beauty',                     an: 1970 },
        { artist: 'The Band',              album: 'Music from Big Pink',                 an: 1968 },
        { artist: 'Lynyrd Skynyrd',        album: 'Second Helping',                      an: 1974 },
        { artist: 'Allman Brothers Band',  album: 'At Fillmore East',                    an: 1971 },
        { artist: 'Derek and the Dominos', album: 'Layla and Other Assorted Love Songs', an: 1970 },
        { artist: 'Deep Purple',           album: 'Machine Head',                        an: 1972 },
    ]
};
