/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/rock/hard-rock.js
   50 albume esențiale de Hard Rock
═══════════════════════════════════════════════════════════════ */

window.hardRockData = {
    gen: 'rock',
    subgen: 'hard-rock',
    label: 'Hard Rock',
    albume: [
        { artist: 'AC/DC',                 album: 'Back in Black',                       an: 1980 },
        { artist: 'AC/DC',                 album: 'Highway to Hell',                     an: 1979 },
        { artist: 'AC/DC',                 album: 'Let There Be Rock',                   an: 1977 },
        { artist: 'Guns N\' Roses',         album: 'Appetite for Destruction',            an: 1987 },
        { artist: 'Guns N\' Roses',         album: 'Use Your Illusion I',                 an: 1991 },
        { artist: 'Aerosmith',             album: 'Toys in the Attic',                   an: 1975 },
        { artist: 'Aerosmith',             album: 'Rocks',                               an: 1976 },
        { artist: 'Van Halen',             album: 'Van Halen',                           an: 1978 },
        { artist: 'Van Halen',             album: '1984',                                an: 1984 },
        { artist: 'Queen',                 album: 'A Night at the Opera',                an: 1975 },
        { artist: 'Queen',                 album: 'News of the World',                   an: 1977 },
        { artist: 'Queen',                 album: 'Jazz',                                an: 1978 },
        { artist: 'Black Sabbath',         album: 'Paranoid',                            an: 1970 },
        { artist: 'Black Sabbath',         album: 'Master of Reality',                   an: 1971 },
        { artist: 'Black Sabbath',         album: 'Heaven and Hell',                     an: 1980 },
        { artist: 'Ozzy Osbourne',         album: 'Blizzard of Ozz',                     an: 1980 },
        { artist: 'Whitesnake',            album: 'Whitesnake',                          an: 1987 },
        { artist: 'Bon Jovi',              album: 'Slippery When Wet',                   an: 1986 },
        { artist: 'Def Leppard',           album: 'Hysteria',                            an: 1987 },
        { artist: 'Def Leppard',           album: 'Pyromania',                           an: 1983 },
        { artist: 'Motley Crue',           album: 'Dr. Feelgood',                        an: 1989 },
        { artist: 'Motley Crue',           album: 'Shout at the Devil',                  an: 1983 },
        { artist: 'KISS',                  album: 'Alive!',                              an: 1975 },
        { artist: 'KISS',                  album: 'Destroyer',                           an: 1976 },
        { artist: 'Alice Cooper',          album: 'Billion Dollar Babies',               an: 1973 },
        { artist: 'Alice Cooper',          album: 'Welcome to My Nightmare',             an: 1975 },
        { artist: 'Deep Purple',           album: 'In Rock',                             an: 1970 },
        { artist: 'Deep Purple',           album: 'Perfect Strangers',                   an: 1984 },
        { artist: 'Scorpions',             album: 'Blackout',                            an: 1982 },
        { artist: 'Scorpions',             album: 'Love at First Sting',                 an: 1984 },
        { artist: 'Judas Priest',          album: 'British Steel',                       an: 1980 },
        { artist: 'Judas Priest',          album: 'Screaming for Vengeance',             an: 1982 },
        { artist: 'Rainbow',               album: 'Rising',                              an: 1976 },
        { artist: 'Dio',                   album: 'Holy Diver',                          an: 1983 },
        { artist: 'Heart',                 album: 'Dreamboat Annie',                     an: 1976 },
        { artist: 'Boston',                album: 'Boston',                              an: 1976 },
        { artist: 'Foreigner',             album: 'Double Vision',                       an: 1978 },
        { artist: 'Bad Company',           album: 'Bad Company',                         an: 1974 },
        { artist: 'Free',                  album: 'Fire and Water',                      an: 1970 },
        { artist: 'Thin Lizzy',            album: 'Jailbreak',                           an: 1976 },
        { artist: 'UFO',                   album: 'Lights Out',                          an: 1977 },
        { artist: 'Blue Öyster Cult',      album: 'Agents of Fortune',                   an: 1976 },
        { artist: 'Nazareth',              album: 'Hair of the Dog',                     an: 1975 },
        { artist: 'ZZ Top',                album: 'Tres Hombres',                        an: 1973 },
        { artist: 'ZZ Top',                album: 'Eliminator',                          an: 1983 },
        { artist: 'Extreme',               album: 'Pornograffitti',                      an: 1990 },
        { artist: 'Mr. Big',               album: 'Lean into It',                        an: 1991 },
        { artist: 'Warrant',               album: 'Dirty Rotten Filthy Stinking Rich',   an: 1989 },
        { artist: 'Dokken',                album: 'Under Lock and Key',                  an: 1985 },
        { artist: 'Ratt',                  album: 'Out of the Cellar',                   an: 1984 },
    ]
};
