/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/rock/punk.js
   50 albume esențiale de Punk Rock
═══════════════════════════════════════════════════════════════ */

window.punkData = {
    gen: 'rock',
    subgen: 'punk',
    label: 'Punk Rock',
    albume: [
        { artist: 'The Clash',             album: 'London Calling',                      an: 1979 },
        { artist: 'The Clash',             album: 'The Clash',                           an: 1977 },
        { artist: 'The Clash',             album: 'Combat Rock',                         an: 1982 },
        { artist: 'Sex Pistols',           album: 'Never Mind the Bollocks',             an: 1977 },
        { artist: 'The Ramones',           album: 'Ramones',                             an: 1976 },
        { artist: 'The Ramones',           album: 'Rocket to Russia',                    an: 1977 },
        { artist: 'The Ramones',           album: 'Road to Ruin',                        an: 1978 },
        { artist: 'The Buzzcocks',         album: 'Singles Going Steady',                an: 1979 },
        { artist: 'Wire',                  album: 'Pink Flag',                           an: 1977 },
        { artist: 'Wire',                  album: 'Chairs Missing',                      an: 1978 },
        { artist: 'The Damned',            album: 'Damned Damned Damned',                an: 1977 },
        { artist: 'The Jam',               album: 'All Mod Cons',                        an: 1978 },
        { artist: 'The Jam',               album: 'Setting Sons',                        an: 1979 },
        { artist: 'Television',            album: 'Marquee Moon',                        an: 1977 },
        { artist: 'Patti Smith',           album: 'Horses',                              an: 1975 },
        { artist: 'Talking Heads',         album: 'Talking Heads: 77',                   an: 1977 },
        { artist: 'Talking Heads',         album: 'Fear of Music',                       an: 1979 },
        { artist: 'Blondie',               album: 'Parallel Lines',                      an: 1978 },
        { artist: 'The Stranglers',        album: 'Rattus Norvegicus',                   an: 1977 },
        { artist: 'Dead Kennedys',         album: 'Fresh Fruit for Rotting Vegetables',  an: 1980 },
        { artist: 'Black Flag',            album: 'Damaged',                             an: 1981 },
        { artist: 'Minor Threat',          album: 'Out of Step',                         an: 1983 },
        { artist: 'Bad Brains',            album: 'Bad Brains',                          an: 1982 },
        { artist: 'Fugazi',                album: 'Repeater',                            an: 1990 },
        { artist: 'Fugazi',                album: 'In on the Kill Taker',                an: 1993 },
        { artist: 'The Misfits',           album: 'Walk Among Us',                       an: 1982 },
        { artist: 'Circle Jerks',          album: 'Group Sex',                           an: 1980 },
        { artist: 'X',                     album: 'Los Angeles',                         an: 1980 },
        { artist: 'Husker Du',             album: 'Zen Arcade',                          an: 1984 },
        { artist: 'Husker Du',             album: 'New Day Rising',                      an: 1985 },
        { artist: 'The Descendents',       album: 'Milo Goes to College',                an: 1982 },
        { artist: 'NOFX',                  album: 'Punk in Drublic',                     an: 1994 },
        { artist: 'Bad Religion',          album: 'Against the Grain',                   an: 1990 },
        { artist: 'Bad Religion',          album: 'Stranger Than Fiction',               an: 1994 },
        { artist: 'Pennywise',             album: 'Unknown Road',                        an: 1993 },
        { artist: 'The Offspring',         album: 'Smash',                               an: 1994 },
        { artist: 'Green Day',             album: 'Kerplunk',                            an: 1992 },
        { artist: 'Rancid',                album: '...And Out Come the Wolves',          an: 1995 },
        { artist: 'Rancid',                album: 'Let\'s Go',                           an: 1994 },
        { artist: 'Op Ivy',                album: 'Energy',                              an: 1989 },
        { artist: 'The Bouncing Souls',    album: 'How I Spent My Summer Vacation',      an: 2001 },
        { artist: 'Lagwagon',              album: 'Trashed',                             an: 1994 },
        { artist: 'Millencolin',           album: 'Life on a Plate',                     an: 1995 },
        { artist: 'Strung Out',            album: 'Suburban Teenage Wasteland Blues',    an: 1996 },
        { artist: 'The Distillers',        album: 'Coral Fang',                          an: 2003 },
        { artist: 'Anti-Flag',             album: 'A New Kind of Army',                  an: 1999 },
        { artist: 'Rise Against',          album: 'The Sufferer & the Witness',          an: 2006 },
        { artist: 'Alkaline Trio',         album: 'Maybe I\'ll Catch Fire',              an: 2000 },
        { artist: 'Social Distortion',     album: 'Social Distortion',                   an: 1990 },
        { artist: 'The Vandals',           album: 'Hitler Bad Vandals Good',             an: 1998 },
    ]
};
