/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/jazz/bebop.js
   50 albume esențiale de Bebop Jazz
   Surse: Rolling Stone, AllMusic Essentials, Rate Your Music
═══════════════════════════════════════════════════════════════ */

window.bebopData = {
    gen: 'jazz',
    subgen: 'bebop',
    label: 'Bebop',
    albume: [
        { artist: 'Miles Davis',           album: 'Kind of Blue',                        an: 1959 },
        { artist: 'John Coltrane',         album: 'A Love Supreme',                      an: 1965 },
        { artist: 'Miles Davis',           album: 'Birth of the Cool',                   an: 1957 },
        { artist: 'Charlie Parker',        album: 'Bird and Diz',                        an: 1952 },
        { artist: 'Charlie Parker',        album: 'Charlie Parker with Strings',         an: 1950 },
        { artist: 'Thelonious Monk',       album: 'Brilliant Corners',                   an: 1957 },
        { artist: 'Thelonious Monk',       album: 'Monk\'s Music',                       an: 1957 },
        { artist: 'Thelonious Monk',       album: 'Thelonious Monk with John Coltrane',  an: 1957 },
        { artist: 'Dizzy Gillespie',       album: 'Dizzy Gillespie at Newport',          an: 1957 },
        { artist: 'Dizzy Gillespie',       album: 'The Greatest of Dizzy Gillespie',     an: 1956 },
        { artist: 'John Coltrane',         album: 'Giant Steps',                         an: 1960 },
        { artist: 'John Coltrane',         album: 'Blue Train',                          an: 1958 },
        { artist: 'John Coltrane',         album: 'My Favorite Things',                  an: 1961 },
        { artist: 'Miles Davis',           album: 'Milestones',                          an: 1958 },
        { artist: 'Miles Davis',           album: 'Cookin\' with the Miles Davis Quintet', an: 1957 },
        { artist: 'Clifford Brown',        album: 'Clifford Brown and Max Roach',        an: 1955 },
        { artist: 'Clifford Brown',        album: 'Study in Brown',                      an: 1955 },
        { artist: 'Bud Powell',            album: 'The Amazing Bud Powell Vol. 1',       an: 1951 },
        { artist: 'Bud Powell',            album: 'The Amazing Bud Powell Vol. 2',       an: 1953 },
        { artist: 'Sonny Rollins',         album: 'Saxophone Colossus',                  an: 1956 },
        { artist: 'Sonny Rollins',         album: 'Way Out West',                        an: 1957 },
        { artist: 'Sonny Rollins',         album: 'A Night at the Village Vanguard',     an: 1957 },
        { artist: 'Art Blakey',            album: 'Moanin\'',                            an: 1958 },
        { artist: 'Art Blakey',            album: 'A Night in Tunisia',                  an: 1960 },
        { artist: 'Horace Silver',         album: 'Song for My Father',                  an: 1965 },
        { artist: 'Horace Silver',         album: 'Blowin\' the Blues Away',             an: 1959 },
        { artist: 'Lee Morgan',            album: 'The Sidewinder',                      an: 1964 },
        { artist: 'Lee Morgan',            album: 'Search for the New Land',             an: 1966 },
        { artist: 'Freddie Hubbard',       album: 'Red Clay',                            an: 1970 },
        { artist: 'Freddie Hubbard',       album: 'Open Sesame',                         an: 1960 },
        { artist: 'Wes Montgomery',        album: 'The Incredible Jazz Guitar',          an: 1960 },
        { artist: 'Wes Montgomery',        album: 'Smokin\' at the Half Note',           an: 1965 },
        { artist: 'Bill Evans',            album: 'Waltz for Debby',                     an: 1962 },
        { artist: 'Bill Evans',            album: 'Portrait in Jazz',                    an: 1960 },
        { artist: 'Oscar Peterson',        album: 'Night Train',                         an: 1963 },
        { artist: 'Oscar Peterson',        album: 'We Get Requests',                     an: 1964 },
        { artist: 'Dexter Gordon',         album: 'Go!',                                 an: 1962 },
        { artist: 'Dexter Gordon',         album: 'Our Man in Paris',                    an: 1963 },
        { artist: 'Cannonball Adderley',   album: 'Somethin\' Else',                     an: 1958 },
        { artist: 'Cannonball Adderley',   album: 'Mercy, Mercy, Mercy! Live at The Club', an: 1967 },
        { artist: 'Chet Baker',            album: 'Chet Baker Sings',                    an: 1954 },
        { artist: 'Chet Baker',            album: 'Chet',                                an: 1959 },
        { artist: 'Charles Mingus',        album: 'Mingus Ah Um',                        an: 1959 },
        { artist: 'Charles Mingus',        album: 'The Black Saint and the Sinner Lady', an: 1963 },
        { artist: 'Thelonious Monk',       album: 'Straight, No Chaser',                 an: 1967 },
        { artist: 'Max Roach',             album: 'We Insist! Freedom Now Suite',        an: 1960 },
        { artist: 'Kenny Dorham',          album: 'Una Mas',                             an: 1963 },
        { artist: 'Hank Mobley',           album: 'Soul Station',                        an: 1960 },
        { artist: 'Wayne Shorter',         album: 'Speak No Evil',                       an: 1966 },
        { artist: 'Wayne Shorter',         album: 'Juju',                                an: 1965 },
    ]
};
