/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/jazz/free-jazz.js
   50 albume esențiale de Free Jazz / Avant-Garde Jazz
═══════════════════════════════════════════════════════════════ */

window.freeJazzData = {
    gen: 'jazz',
    subgen: 'free-jazz',
    label: 'Free Jazz',
    albume: [
        { artist: 'John Coltrane',         album: 'Ascension',                           an: 1966 },
        { artist: 'John Coltrane',         album: 'Interstellar Space',                  an: 1974 },
        { artist: 'John Coltrane',         album: 'Expression',                          an: 1967 },
        { artist: 'Ornette Coleman',       album: 'The Shape of Jazz to Come',           an: 1959 },
        { artist: 'Ornette Coleman',       album: 'Free Jazz: A Collective Improvisation', an: 1961 },
        { artist: 'Ornette Coleman',       album: 'Change of the Century',               an: 1960 },
        { artist: 'Ornette Coleman',       album: 'This Is Our Music',                   an: 1961 },
        { artist: 'Albert Ayler',          album: 'Spiritual Unity',                     an: 1965 },
        { artist: 'Albert Ayler',          album: 'Bells',                               an: 1965 },
        { artist: 'Albert Ayler',          album: 'Lörrach / Paris 1966',                an: 2011 },
        { artist: 'Sun Ra',                album: 'The Heliocentric Worlds of Sun Ra',   an: 1965 },
        { artist: 'Sun Ra',                album: 'Space Is the Place',                  an: 1973 },
        { artist: 'Sun Ra',                album: 'Lanquidity',                          an: 1978 },
        { artist: 'Cecil Taylor',          album: 'Unit Structures',                     an: 1966 },
        { artist: 'Cecil Taylor',          album: 'Conquistador!',                       an: 1966 },
        { artist: 'Cecil Taylor',          album: 'Silent Tongues',                      an: 1975 },
        { artist: 'Archie Shepp',          album: 'Four for Trane',                      an: 1964 },
        { artist: 'Archie Shepp',          album: 'Fire Music',                          an: 1965 },
        { artist: 'Don Cherry',            album: 'Complete Communion',                  an: 1966 },
        { artist: 'Don Cherry',            album: 'Relativity Suite',                    an: 1974 },
        { artist: 'Charles Mingus',        album: 'The Black Saint and the Sinner Lady', an: 1963 },
        { artist: 'Charles Mingus',        album: 'Mingus Mingus Mingus Mingus Mingus',  an: 1963 },
        { artist: 'Eric Dolphy',           album: 'Out to Lunch!',                       an: 1964 },
        { artist: 'Eric Dolphy',           album: 'Out There',                           an: 1960 },
        { artist: 'Eric Dolphy',           album: 'Last Date',                           an: 1964 },
        { artist: 'Anthony Braxton',       album: 'For Alto',                            an: 1971 },
        { artist: 'Anthony Braxton',       album: 'New York, Fall 1974',                 an: 1975 },
        { artist: 'AACM',                  album: 'Numbers 1 & 2',                       an: 1967 },
        { artist: 'Art Ensemble of Chicago', album: 'People in Sorrow',                  an: 1969 },
        { artist: 'Art Ensemble of Chicago', album: 'Nice Guys',                         an: 1979 },
        { artist: 'Pharoah Sanders',       album: 'Karma',                               an: 1969 },
        { artist: 'Pharoah Sanders',       album: 'Tauhid',                              an: 1967 },
        { artist: 'Pharoah Sanders',       album: 'Jewels of Thought',                   an: 1969 },
        { artist: 'Rashied Ali',           album: 'Rashied Ali Quintet',                 an: 1975 },
        { artist: 'Marion Brown',          album: 'Afternoon of a Georgia Faun',         an: 1970 },
        { artist: 'Sam Rivers',            album: 'Fuchsia Swing Song',                  an: 1965 },
        { artist: 'Roswell Rudd',          album: 'Everywhere',                          an: 1966 },
        { artist: 'Sunny Murray',          album: 'Sunny Murray',                        an: 1966 },
        { artist: 'Paul Bley',             album: 'Open, to Love',                       an: 1974 },
        { artist: 'Paul Bley',             album: 'Footloose!',                          an: 1963 },
        { artist: 'Joseph Jarman',         album: 'Song For',                            an: 1967 },
        { artist: 'Roscoe Mitchell',       album: 'Sound',                               an: 1966 },
        { artist: 'Dave Holland',          album: 'Conference of the Birds',             an: 1973 },
        { artist: 'Old and New Dreams',    album: 'Old and New Dreams',                  an: 1979 },
        { artist: 'Henry Threadgill',      album: 'You Know the Number',                 an: 1986 },
        { artist: 'Muhal Richard Abrams',  album: 'Levels and Degrees of Light',         an: 1968 },
        { artist: 'William Parker',        album: 'O\'Neal\'s Porch',                    an: 2002 },
        { artist: 'Ken Vandermark',        album: 'Caffeine',                            an: 1995 },
        { artist: 'Matthew Shipp',         album: 'New Orbit',                           an: 1999 },
        { artist: 'Peter Brötzmann',       album: 'Machine Gun',                         an: 1968 },
    ]
};
