/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/jazz/fusion.js
   50 albume esențiale de Jazz Fusion
═══════════════════════════════════════════════════════════════ */

window.fusionData = {
    gen: 'jazz',
    subgen: 'fusion',
    label: 'Jazz Fusion',
    albume: [
        { artist: 'Miles Davis',           album: 'Bitches Brew',                        an: 1970 },
        { artist: 'Miles Davis',           album: 'In a Silent Way',                     an: 1969 },
        { artist: 'Miles Davis',           album: 'On the Corner',                       an: 1972 },
        { artist: 'Weather Report',        album: 'Heavy Weather',                       an: 1977 },
        { artist: 'Weather Report',        album: 'Mysterious Traveller',                an: 1974 },
        { artist: 'Weather Report',        album: 'Sweetnighter',                        an: 1973 },
        { artist: 'Mahavishnu Orchestra',  album: 'The Inner Mounting Flame',            an: 1971 },
        { artist: 'Mahavishnu Orchestra',  album: 'Birds of Fire',                       an: 1973 },
        { artist: 'Return to Forever',     album: 'Romantic Warrior',                    an: 1976 },
        { artist: 'Return to Forever',     album: 'Romantic Warrior',                    an: 1976 },
        { artist: 'Chick Corea',           album: 'Return to Forever',                   an: 1972 },
        { artist: 'Chick Corea',           album: 'Hymn of the Seventh Galaxy',          an: 1973 },
        { artist: 'Herbie Hancock',        album: 'Head Hunters',                        an: 1973 },
        { artist: 'Herbie Hancock',        album: 'Thrust',                              an: 1974 },
        { artist: 'Pat Metheny Group',     album: 'Offramp',                             an: 1982 },
        { artist: 'Pat Metheny Group',     album: 'Still Life (Talking)',                an: 1987 },
        { artist: 'Pat Metheny Group',     album: 'Travels',                             an: 1983 },
        { artist: 'John McLaughlin',       album: 'Shakti',                              an: 1976 },
        { artist: 'John McLaughlin',       album: 'Electric Guitarist',                  an: 1978 },
        { artist: 'Tony Williams Lifetime',album: 'Emergency!',                          an: 1969 },
        { artist: 'Soft Machine',          album: 'Third',                               an: 1970 },
        { artist: 'Soft Machine',          album: 'Six',                                 an: 1973 },
        { artist: 'Brand X',               album: 'Unorthodox Behaviour',                an: 1976 },
        { artist: 'Headhunters',           album: 'Survival of the Fittest',             an: 1975 },
        { artist: 'Stanley Clarke',        album: 'School Days',                         an: 1976 },
        { artist: 'Stanley Clarke',        album: 'Journey to Love',                     an: 1975 },
        { artist: 'Larry Coryell',         album: 'Spaces',                              an: 1970 },
        { artist: 'Billy Cobham',          album: 'Spectrum',                            an: 1973 },
        { artist: 'Billy Cobham',          album: 'Total Eclipse',                       an: 1974 },
        { artist: 'John Scofield',         album: 'Loud Jazz',                           an: 1987 },
        { artist: 'John Scofield',         album: 'Blue Matter',                         an: 1987 },
        { artist: 'Mike Stern',            album: 'Upside Downside',                     an: 1986 },
        { artist: 'Mike Stern',            album: 'Time in Place',                       an: 1988 },
        { artist: 'Marcus Miller',         album: 'The Sun Don\'t Lie',                  an: 1993 },
        { artist: 'Marcus Miller',         album: 'Tales',                               an: 1995 },
        { artist: 'Yellowjackets',         album: 'Yellowjackets',                       an: 1981 },
        { artist: 'Yellowjackets',         album: 'Mirage a Trois',                      an: 1983 },
        { artist: 'Steps Ahead',           album: 'Steps Ahead',                         an: 1983 },
        { artist: 'Bob Berg',              album: 'Short Stories',                       an: 1987 },
        { artist: 'Tribal Tech',           album: 'Dr. Hee',                             an: 1987 },
        { artist: 'Casiopea',              album: 'Mint Jams',                           an: 1982 },
        { artist: 'T Square',              album: 'Truth',                               an: 1990 },
        { artist: 'Uzeb',                  album: 'Fast Emotion',                        an: 1985 },
        { artist: 'Incognito',             album: 'Inside Life',                         an: 1991 },
        { artist: 'Incognito',             album: 'Positivity',                          an: 1993 },
        { artist: 'Medeski Martin & Wood', album: 'Shack-man',                           an: 1996 },
        { artist: 'Snarky Puppy',          album: 'We Like It Here',                     an: 2014 },
        { artist: 'Snarky Puppy',          album: 'Family Dinner Volume 2',              an: 2016 },
        { artist: 'Kamasi Washington',     album: 'The Epic',                            an: 2015 },
        { artist: 'Thundercat',            album: 'Drunk',                               an: 2017 },
    ]
};
