/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/jazz/jazz-vocal.js
   50 albume esențiale de Jazz Vocal Contemporan
   Caro Emerald, Diana Krall, Michael Bublé, Norah Jones, Jamie Cullum
═══════════════════════════════════════════════════════════════ */

window.jazzVocalData = {
    gen: 'jazz',
    subgen: 'jazz-vocal',
    label: 'Jazz Vocal Contemporan',
    albume: [
        { artist: 'Norah Jones',           album: 'Come Away with Me',                   an: 2002 },
        { artist: 'Norah Jones',           album: 'Feels Like Home',                     an: 2004 },
        { artist: 'Norah Jones',           album: 'Not Too Late',                        an: 2007 },
        { artist: 'Norah Jones',           album: 'The Fall',                            an: 2009 },
        { artist: 'Norah Jones',           album: 'Day Breaks',                          an: 2016 },
        { artist: 'Caro Emerald',          album: 'Deleted Scenes from the Cutting Room Floor', an: 2010 },
        { artist: 'Caro Emerald',          album: 'The Shocking Miss Emerald',           an: 2013 },
        { artist: 'Diana Krall',           album: 'When I Look in Your Eyes',            an: 1999 },
        { artist: 'Diana Krall',           album: 'The Look of Love',                    an: 2001 },
        { artist: 'Diana Krall',           album: 'Live in Paris',                       an: 2002 },
        { artist: 'Diana Krall',           album: 'Quiet Nights',                        an: 2009 },
        { artist: 'Diana Krall',           album: 'Wallflower',                          an: 2015 },
        { artist: 'Diana Krall',           album: 'This Dream of You',                   an: 2020 },
        { artist: 'Michael Bublé',         album: 'It\'s Time',                          an: 2005 },
        { artist: 'Michael Bublé',         album: 'Call Me Irresponsible',               an: 2007 },
        { artist: 'Michael Bublé',         album: 'Crazy Love',                          an: 2009 },
        { artist: 'Michael Bublé',         album: 'To Be Loved',                         an: 2013 },
        { artist: 'Michael Bublé',         album: 'Nobody but Me',                       an: 2016 },
        { artist: 'Jamie Cullum',          album: 'Twentysomething',                     an: 2003 },
        { artist: 'Jamie Cullum',          album: 'Catching Tales',                      an: 2005 },
        { artist: 'Jamie Cullum',          album: 'The Pursuit',                         an: 2009 },
        { artist: 'Jamie Cullum',          album: 'Interlude',                           an: 2014 },
        { artist: 'Jamie Cullum',          album: 'Taller',                              an: 2019 },
        { artist: 'Amy Winehouse',         album: 'Back to Black',                       an: 2006 },
        { artist: 'Amy Winehouse',         album: 'Frank',                               an: 2003 },
        { artist: 'Tony Bennett',          album: 'Duets: An American Classic',          an: 2006 },
        { artist: 'Tony Bennett',          album: 'Cheek to Cheek',                      an: 2014 },
        { artist: 'Rod Stewart',           album: 'It Had to Be You: The Great American Songbook', an: 2002 },
        { artist: 'Harry Connick Jr.',     album: 'We Are in Love',                      an: 1990 },
        { artist: 'Harry Connick Jr.',     album: 'She',                                 an: 1994 },
        { artist: 'Harry Connick Jr.',     album: 'Your Songs',                          an: 2009 },
        { artist: 'Stacey Kent',           album: 'The Changing Lights',                 an: 2013 },
        { artist: 'Stacey Kent',           album: 'I Know I Dream',                      an: 2017 },
        { artist: 'Jane Monheit',          album: 'Never Never Land',                    an: 2000 },
        { artist: 'Jane Monheit',          album: 'Taking a Chance on Love',             an: 2004 },
        { artist: 'Madeleine Peyroux',     album: 'Careless Love',                       an: 2004 },
        { artist: 'Madeleine Peyroux',     album: 'Half the Perfect World',              an: 2006 },
        { artist: 'Melody Gardot',         album: 'Worrisome Heart',                     an: 2008 },
        { artist: 'Melody Gardot',         album: 'My One and Only Thrill',              an: 2009 },
        { artist: 'Melody Gardot',         album: 'The Absence',                         an: 2012 },
        { artist: 'Roberta Gambarini',     album: 'Easy to Love',                        an: 2006 },
        { artist: 'Patricia Barber',       album: 'Modern Cool',                         an: 1998 },
        { artist: 'Cassandra Wilson',      album: 'New Moon Daughter',                   an: 1995 },
        { artist: 'Cassandra Wilson',      album: 'Belly of the Sun',                    an: 2002 },
        { artist: 'Karrin Allyson',        album: 'Imagina: Songs of Brazil',            an: 2008 },
        { artist: 'Eliane Elias',          album: 'Bossa Nova Stories',                  an: 2008 },
        { artist: 'Eliane Elias',          album: 'Dance of Time',                       an: 2017 },
        { artist: 'Hiromi',                album: 'Place to Be',                         an: 2009 },
        { artist: 'Gregory Porter',        album: 'Liquid Spirit',                       an: 2013 },
        { artist: 'Gregory Porter',        album: 'Take Me to the Alley',                an: 2016 },
    ]
};
