/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/jazz/smooth-jazz.js
   50 albume esențiale de Smooth Jazz / Contemporary Jazz
═══════════════════════════════════════════════════════════════ */

window.smoothJazzData = {
    gen: 'jazz',
    subgen: 'smooth-jazz',
    label: 'Smooth Jazz',
    albume: [
        { artist: 'Kenny G',               album: 'Breathless',                          an: 1992 },
        { artist: 'Kenny G',               album: 'Duotones',                            an: 1986 },
        { artist: 'George Benson',         album: 'Breezin\'',                           an: 1976 },
        { artist: 'George Benson',         album: 'Give Me the Night',                   an: 1980 },
        { artist: 'Grover Washington Jr.', album: 'Winelight',                           an: 1980 },
        { artist: 'Grover Washington Jr.', album: 'Mister Magic',                        an: 1975 },
        { artist: 'Dave Grusin',           album: 'Mountain Dance',                      an: 1980 },
        { artist: 'Bob James',             album: 'Two',                                 an: 1975 },
        { artist: 'Bob James',             album: 'Touchdown',                           an: 1978 },
        { artist: 'Spyro Gyra',            album: 'Morning Dance',                       an: 1979 },
        { artist: 'Earl Klugh',            album: 'Two of a Kind',                       an: 1982 },
        { artist: 'Earl Klugh',            album: 'Magic in Your Eyes',                  an: 1978 },
        { artist: 'Al Jarreau',            album: 'Breakin\' Away',                      an: 1981 },
        { artist: 'Al Jarreau',            album: 'We Got By',                           an: 1975 },
        { artist: 'Fourplay',              album: 'Fourplay',                            an: 1991 },
        { artist: 'Fourplay',              album: 'Between the Sheets',                  an: 1993 },
        { artist: 'Lee Ritenour',          album: 'Rit',                                 an: 1981 },
        { artist: 'Lee Ritenour',          album: 'Captain Fingers',                     an: 1977 },
        { artist: 'Chuck Mangione',        album: 'Feels So Good',                       an: 1977 },
        { artist: 'Najee',                 album: 'Najee\'s Theme',                      an: 1986 },
        { artist: 'David Sanborn',         album: 'A Change of Heart',                   an: 1987 },
        { artist: 'David Sanborn',         album: 'Hideaway',                            an: 1980 },
        { artist: 'Boney James',           album: 'Seduction',                           an: 1995 },
        { artist: 'Rick Braun',            album: 'Intimate Secrets',                    an: 1999 },
        { artist: 'Brian Culbertson',      album: 'After Midnight',                      an: 2004 },
        { artist: 'Norman Brown',          album: 'After the Storm',                     an: 1994 },
        { artist: 'Jonathan Butler',       album: 'Jonathan Butler',                     an: 1987 },
        { artist: 'Russ Freeman',          album: 'Hand Built by Robots',                an: 2007 },
        { artist: 'Acoustic Alchemy',      album: 'Red Dust & Spanish Lace',             an: 1987 },
        { artist: 'Acoustic Alchemy',      album: 'Natural Elements',                   an: 1988 },
        { artist: 'Gerald Albright',       album: 'Bermuda Nights',                      an: 1988 },
        { artist: 'Kirk Whalum',           album: 'And You Know That!',                  an: 1988 },
        { artist: 'Hiroshima',             album: 'Go',                                  an: 1987 },
        { artist: 'Marion Meadows',        album: 'For Lovers Only',                     an: 1992 },
        { artist: 'Peter White',           album: 'Reflections',                         an: 1994 },
        { artist: 'Dave Koz',              album: 'Dave Koz',                            an: 1990 },
        { artist: 'Dave Koz',              album: 'Lucky Man',                           an: 1993 },
        { artist: 'Jeff Lorber',           album: 'In the Heart of the City',            an: 1990 },
        { artist: 'Pieces of a Dream',     album: 'Goodbye Manhattan',                   an: 1982 },
        { artist: 'Tom Scott',             album: 'Tom Cat',                             an: 1975 },
        { artist: 'Paul Hardcastle',       album: 'Rain Forest',                         an: 1991 },
        { artist: 'Michael Franks',        album: 'The Art of Tea',                      an: 1975 },
        { artist: 'George Duke',           album: 'Reach for It',                        an: 1977 },
        { artist: 'Stanley Turrentine',    album: 'Sugar',                               an: 1971 },
        { artist: 'Lonnie Liston Smith',   album: 'Expansions',                          an: 1975 },
        { artist: 'Ramsey Lewis',          album: 'Sun Goddess',                         an: 1974 },
        { artist: 'Herbie Hancock',        album: 'Head Hunters',                        an: 1973 },
        { artist: 'Herbie Hancock',        album: 'Thrust',                              an: 1974 },
        { artist: 'George Benson',         album: 'In Flight',                           an: 1977 },
        { artist: 'Pat Metheny',           album: 'Pat Metheny Group',                   an: 1978 },
    ]
};
