/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/soul/neo-soul.js
   50 albume esențiale de Neo Soul / R&B Contemporan
═══════════════════════════════════════════════════════════════ */

window.neoSoulData = {
    gen: 'soul',
    subgen: 'neo-soul',
    label: 'Neo Soul / R&B',
    albume: [
        { artist: 'Amy Winehouse',         album: 'Back to Black',                       an: 2006 },
        { artist: 'Amy Winehouse',         album: 'Frank',                               an: 2003 },
        { artist: 'Adele',                 album: '21',                                  an: 2011 },
        { artist: 'Adele',                 album: '25',                                  an: 2015 },
        { artist: 'Adele',                 album: '30',                                  an: 2021 },
        { artist: 'Adele',                 album: '19',                                  an: 2008 },
        { artist: 'Duffy',                 album: 'Rockferry',                           an: 2008 },
        { artist: 'Joss Stone',            album: 'The Soul Sessions',                   an: 2003 },
        { artist: 'Joss Stone',            album: 'Mind Body & Soul',                    an: 2004 },
        { artist: 'Joss Stone',            album: 'Colour Me Free',                      an: 2009 },
        { artist: 'D\'Angelo',             album: 'Voodoo',                              an: 2000 },
        { artist: 'D\'Angelo',             album: 'Black Messiah',                       an: 2014 },
        { artist: 'Erykah Badu',           album: 'Baduizm',                             an: 1997 },
        { artist: 'Erykah Badu',           album: 'Mama\'s Gun',                         an: 2000 },
        { artist: 'Alicia Keys',           album: 'Songs in A Minor',                    an: 2001 },
        { artist: 'Alicia Keys',           album: 'The Diary of Alicia Keys',            an: 2003 },
        { artist: 'Alicia Keys',           album: 'As I Am',                             an: 2007 },
        { artist: 'John Legend',           album: 'Get Lifted',                          an: 2004 },
        { artist: 'John Legend',           album: 'Once Again',                          an: 2006 },
        { artist: 'John Legend',           album: 'Evolver',                             an: 2008 },
        { artist: 'Maxwell',               album: 'Maxwell\'s Urban Hang Suite',         an: 1996 },
        { artist: 'Maxwell',               album: 'BLACKsummers\'night',                 an: 2009 },
        { artist: 'Lauryn Hill',           album: 'The Miseducation of Lauryn Hill',     an: 1998 },
        { artist: 'Mary J. Blige',         album: 'What\'s the 411?',                    an: 1992 },
        { artist: 'Mary J. Blige',         album: 'My Life',                             an: 1994 },
        { artist: 'Mary J. Blige',         album: 'Share My World',                      an: 1997 },
        { artist: 'India.Arie',            album: 'Acoustic Soul',                       an: 2001 },
        { artist: 'India.Arie',            album: 'Voyage to India',                     an: 2002 },
        { artist: 'Jill Scott',            album: 'Who Is Jill Scott?',                  an: 2000 },
        { artist: 'Jill Scott',            album: 'Beautifully Human',                   an: 2004 },
        { artist: 'Musiq Soulchild',       album: 'Aijuswanaseing',                      an: 2000 },
        { artist: 'Anthony Hamilton',      album: 'Comin\' from Where I\'m From',        an: 2003 },
        { artist: 'Ledisi',                album: 'Lost & Found',                        an: 2007 },
        { artist: 'Corinne Bailey Rae',    album: 'Corinne Bailey Rae',                  an: 2006 },
        { artist: 'Corinne Bailey Rae',    album: 'The Sea',                             an: 2010 },
        { artist: 'Leon Bridges',          album: 'Coming Home',                         an: 2015 },
        { artist: 'Leon Bridges',          album: 'Good Thing',                          an: 2018 },
        { artist: 'Leon Bridges',          album: 'Gold-Diggers Sound',                  an: 2021 },
        { artist: 'H.E.R.',               album: 'H.E.R.',                              an: 2017 },
        { artist: 'H.E.R.',               album: 'Back of My Mind',                     an: 2021 },
        { artist: 'Jazmine Sullivan',      album: 'Fearless',                            an: 2008 },
        { artist: 'Jazmine Sullivan',      album: 'Heaux Tales',                         an: 2021 },
        { artist: 'Bruno Mars',            album: 'Unorthodox Jukebox',                  an: 2012 },
        { artist: 'Bruno Mars',            album: '24K Magic',                           an: 2016 },
        { artist: 'Anderson .Paak',        album: 'Malibu',                              an: 2016 },
        { artist: 'Anderson .Paak',        album: 'Ventura',                             an: 2019 },
        { artist: 'Silk Sonic',            album: 'An Evening with Silk Sonic',          an: 2021 },
        { artist: 'SZA',                   album: 'CTRL',                                an: 2017 },
        { artist: 'SZA',                   album: 'SOS',                                 an: 2022 },
        { artist: 'Lianne La Havas',       album: 'Blood',                               an: 2015 },
    ]
};
