/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/folk/indie-folk.js
   50 albume esențiale de Indie Folk & Americana (2000-2024)
═══════════════════════════════════════════════════════════════ */

window.indieFolkData = {
    gen: 'folk',
    subgen: 'indie-folk',
    label: 'Indie Folk & Americana',
    albume: [
        { artist: 'Mumford & Sons',        album: 'Sigh No More',                        an: 2009 },
        { artist: 'Mumford & Sons',        album: 'Babel',                               an: 2012 },
        { artist: 'Mumford & Sons',        album: 'Wilder Mind',                         an: 2015 },
        { artist: 'The Lumineers',         album: 'The Lumineers',                       an: 2012 },
        { artist: 'The Lumineers',         album: 'Cleopatra',                           an: 2016 },
        { artist: 'The Lumineers',         album: 'III',                                 an: 2019 },
        { artist: 'Fleet Foxes',           album: 'Fleet Foxes',                         an: 2008 },
        { artist: 'Fleet Foxes',           album: 'Helplessness Blues',                  an: 2011 },
        { artist: 'Fleet Foxes',           album: 'Shore',                               an: 2020 },
        { artist: 'Bon Iver',              album: 'For Emma, Forever Ago',               an: 2008 },
        { artist: 'Bon Iver',              album: 'Bon Iver, Bon Iver',                  an: 2011 },
        { artist: 'Iron & Wine',           album: 'Our Endless Numbered Days',           an: 2004 },
        { artist: 'Iron & Wine',           album: 'The Shepherd\'s Dog',                 an: 2007 },
        { artist: 'Noah and the Whale',    album: 'The First Days of Spring',            an: 2009 },
        { artist: 'Of Monsters and Men',   album: 'My Head Is an Animal',               an: 2011 },
        { artist: 'Of Monsters and Men',   album: 'Beneath the Skin',                   an: 2015 },
        { artist: 'The Head and the Heart', album: 'The Head and the Heart',             an: 2011 },
        { artist: 'Lord Huron',            album: 'Lonesome Dreams',                     an: 2012 },
        { artist: 'Lord Huron',            album: 'Strange Trails',                      an: 2015 },
        { artist: 'The Decemberists',      album: 'The Crane Wife',                      an: 2006 },
        { artist: 'The Decemberists',      album: 'The King Is Dead',                    an: 2011 },
        { artist: 'Sufjan Stevens',        album: 'Illinois',                            an: 2005 },
        { artist: 'Sufjan Stevens',        album: 'Carrie & Lowell',                     an: 2015 },
        { artist: 'Josh Ritter',           album: 'The Animal Years',                    an: 2006 },
        { artist: 'Josh Ritter',           album: 'So Runs the World Away',              an: 2010 },
        { artist: 'Gregory Alan Isakov',   album: 'This Empty Northern Hemisphere',      an: 2009 },
        { artist: 'Gregory Alan Isakov',   album: 'Evening Machines',                    an: 2018 },
        { artist: 'Gillian Welch',         album: 'Time (The Revelator)',                an: 2001 },
        { artist: 'Gillian Welch',         album: 'Soul Journey',                        an: 2003 },
        { artist: 'Patty Griffin',         album: 'Living with Ghosts',                  an: 1996 },
        { artist: 'Patty Griffin',         album: 'Children Running Through',            an: 2007 },
        { artist: 'Ryan Adams',            album: 'Gold',                                an: 2001 },
        { artist: 'Ryan Adams',            album: 'Heartbreaker',                        an: 2000 },
        { artist: 'Ray LaMontagne',        album: 'Trouble',                             an: 2004 },
        { artist: 'Ray LaMontagne',        album: 'Till the Sun Turns Black',            an: 2006 },
        { artist: 'Ray LaMontagne',        album: 'Gossip in the Grain',                 an: 2008 },
        { artist: 'Punch Brothers',        album: 'Who\'s Feeling Young Now?',           an: 2012 },
        { artist: 'Old Crow Medicine Show', album: 'O.C.M.S.',                           an: 2004 },
        { artist: 'Hozier',                album: 'Hozier',                              an: 2014 },
        { artist: 'Hozier',                album: 'Wasteland, Baby!',                    an: 2019 },
        { artist: 'Hozier',                album: 'Unreal Unearth',                      an: 2023 },
        { artist: 'Andrew Bird',           album: 'Noble Beast',                         an: 2009 },
        { artist: 'Caamp',                 album: 'By and By',                           an: 2019 },
        { artist: 'Noah Kahan',            album: 'Stick Season',                        an: 2022 },
        { artist: 'Noah Kahan',            album: 'We\'ll All Be Here Forever',          an: 2023 },
        { artist: 'Phoebe Bridgers',       album: 'Stranger in the Alps',               an: 2017 },
        { artist: 'Phoebe Bridgers',       album: 'Punisher',                            an: 2020 },
        { artist: 'boygenius',             album: 'The Record',                          an: 2023 },
        { artist: 'First Aid Kit',         album: 'The Lion\'s Roar',                    an: 2012 },
        { artist: 'First Aid Kit',         album: 'Stay Gold',                           an: 2014 },
    ]
};
