/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/blues/blues-rock.js
   50 albume esențiale de Blues Rock Contemporan (1990-2024)
═══════════════════════════════════════════════════════════════ */

window.bluesRockData = {
    gen: 'blues',
    subgen: 'blues-rock',
    label: 'Blues Rock Contemporan',
    albume: [
        { artist: 'Stevie Ray Vaughan',    album: 'Texas Flood',                         an: 1983 },
        { artist: 'Stevie Ray Vaughan',    album: 'In Step',                             an: 1989 },
        { artist: 'Gary Moore',            album: 'Still Got the Blues',                 an: 1990 },
        { artist: 'Gary Moore',            album: 'After Hours',                         an: 1992 },
        { artist: 'John Mayer',            album: 'Continuum',                           an: 2006 },
        { artist: 'John Mayer',            album: 'Where the Light Is',                  an: 2008 },
        { artist: 'John Mayer',            album: 'Born and Raised',                     an: 2012 },
        { artist: 'John Mayer',            album: 'The Search for Everything',           an: 2017 },
        { artist: 'Gary Clark Jr.',        album: 'Blak and Blu',                        an: 2012 },
        { artist: 'Gary Clark Jr.',        album: 'The Story of Sonny Boy Slim',         an: 2015 },
        { artist: 'Gary Clark Jr.',        album: 'This Land',                           an: 2019 },
        { artist: 'Joe Bonamassa',         album: 'Blues Deluxe',                        an: 2003 },
        { artist: 'Joe Bonamassa',         album: 'Dust Bowl',                           an: 2011 },
        { artist: 'Joe Bonamassa',         album: 'Different Shades of Blue',            an: 2014 },
        { artist: 'Joe Bonamassa',         album: 'Royal Tea',                           an: 2020 },
        { artist: 'The Black Keys',        album: 'Brothers',                            an: 2010 },
        { artist: 'The Black Keys',        album: 'El Camino',                           an: 2011 },
        { artist: 'The Black Keys',        album: 'Attack & Release',                    an: 2008 },
        { artist: 'Jack White',            album: 'Blunderbuss',                         an: 2012 },
        { artist: 'The White Stripes',     album: 'Elephant',                            an: 2003 },
        { artist: 'The White Stripes',     album: 'Icky Thump',                          an: 2007 },
        { artist: 'Tedeschi Trucks Band',  album: 'Revelator',                           an: 2011 },
        { artist: 'Tedeschi Trucks Band',  album: 'Made Up Mind',                        an: 2013 },
        { artist: 'Tedeschi Trucks Band',  album: 'Signs',                               an: 2019 },
        { artist: 'Robert Cray',           album: 'Strong Persuader',                    an: 1986 },
        { artist: 'Robert Cray',           album: 'Take Your Shoes Off',                 an: 1999 },
        { artist: 'Kenny Wayne Shepherd',  album: 'Ledbetter Heights',                   an: 1995 },
        { artist: 'Kenny Wayne Shepherd',  album: 'Trouble Is',                          an: 1997 },
        { artist: 'Kenny Wayne Shepherd',  album: 'Goin\' Home',                         an: 2014 },
        { artist: 'Jonny Lang',            album: 'Lie to Me',                           an: 1997 },
        { artist: 'Jonny Lang',            album: 'Wander This World',                   an: 1998 },
        { artist: 'Robben Ford',           album: 'Talk to Your Daughter',               an: 1988 },
        { artist: 'Robben Ford',           album: 'Bringing It Back Home',               an: 2013 },
        { artist: 'Beth Hart',             album: 'War in My Mind',                      an: 2019 },
        { artist: 'Beth Hart',             album: 'Fire on the Floor',                   an: 2016 },
        { artist: 'Beth Hart',             album: 'A Tribute to Led Zeppelin',           an: 2022 },
        { artist: 'Joe Bonamassa',         album: 'Live at Carnegie Hall',               an: 2016 },
        { artist: 'Rory Gallagher',        album: 'Irish Tour \'74',                     an: 1974 },
        { artist: 'Eric Clapton',          album: 'From the Cradle',                     an: 1994 },
        { artist: 'Eric Clapton',          album: 'Riding with the King',                an: 2000 },
        { artist: 'Eric Clapton',          album: 'Me and Mr. Johnson',                  an: 2004 },
        { artist: 'Keb\' Mo\'',            album: 'BLUESAmericana',                      an: 2014 },
        { artist: 'Keb\' Mo\'',            album: 'Oklahoma',                            an: 2019 },
        { artist: 'Shemekia Copeland',     album: 'Uncivil War',                         an: 2020 },
        { artist: 'Marcus King',           album: 'El Dorado',                           an: 2020 },
        { artist: 'Marcus King',           album: 'Young Blood',                         an: 2022 },
        { artist: 'Christone Kingfish Ingram', album: 'Kingfish',                        an: 2019 },
        { artist: 'Christone Kingfish Ingram', album: '662',                             an: 2021 },
        { artist: 'John Lee Hooker',       album: 'The Healer',                          an: 1989 },
        { artist: 'Buddy Guy',             album: 'Damn Right I\'ve Got the Blues',      an: 1991 },
    ]
};
