/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/blues/chicago-blues.js
   50 albume esențiale de Chicago Blues
═══════════════════════════════════════════════════════════════ */

window.chicagoBluesData = {
    gen: 'blues',
    subgen: 'chicago-blues',
    label: 'Chicago Blues',
    albume: [
        { artist: 'Muddy Waters',          album: 'The Best of Muddy Waters',            an: 1958 },
        { artist: 'Muddy Waters',          album: 'Electric Mud',                        an: 1968 },
        { artist: 'Muddy Waters',          album: 'Fathers and Sons',                    an: 1969 },
        { artist: 'Howlin\' Wolf',         album: 'Rockin\' Chair Album',                an: 1962 },
        { artist: 'Howlin\' Wolf',         album: 'Evil',                                an: 1969 },
        { artist: 'Little Walter',         album: 'Hate to See You Go',                  an: 1969 },
        { artist: 'Sonny Boy Williamson',  album: 'Keep It to Ourselves',                an: 1990 },
        { artist: 'Otis Rush',             album: 'Cold Day in Hell',                    an: 1975 },
        { artist: 'Magic Sam',             album: 'Black Magic',                         an: 1969 },
        { artist: 'Buddy Guy',             album: 'Stone Crazy!',                        an: 1961 },
        { artist: 'Buddy Guy',             album: 'Slippin\' In',                        an: 1994 },
        { artist: 'Junior Wells',          album: 'It\'s My Life, Baby!',                an: 1966 },
        { artist: 'Junior Wells',          album: 'Coming at You',                       an: 1968 },
        { artist: 'Jimmy Rogers',          album: 'Chicago Bound',                       an: 1976 },
        { artist: 'Koko Taylor',           album: 'I Got What It Takes',                 an: 1975 },
        { artist: 'Koko Taylor',           album: 'The Earthshaker',                     an: 1978 },
        { artist: 'Lonnie Brooks',         album: 'Bayou Lightning',                     an: 1979 },
        { artist: 'Jimmy Johnson',         album: 'Johnson\'s Whacks',                   an: 1979 },
        { artist: 'Hound Dog Taylor',      album: 'Hound Dog Taylor and the HouseRockers', an: 1971 },
        { artist: 'Hound Dog Taylor',      album: 'Natural Boogie',                      an: 1974 },
        { artist: 'Son Seals',             album: 'The Son Seals Blues Band',            an: 1973 },
        { artist: 'Son Seals',             album: 'Midnight Son',                        an: 1976 },
        { artist: 'Fenton Robinson',       album: 'Somebody Loan Me a Dime',             an: 1974 },
        { artist: 'A.C. Reed',             album: 'I\'m in the Wrong Business!',         an: 1987 },
        { artist: 'Billy Boy Arnold',      album: 'Blow the Back Off It',                an: 1995 },
        { artist: 'Luther Allison',        album: 'Night Life',                          an: 1976 },
        { artist: 'L.C. Thurman',          album: 'Comin\' Up',                          an: 1982 },
        { artist: 'Big Walter Horton',     album: 'Big Walter Horton with Carey Bell',   an: 1972 },
        { artist: 'James Cotton',          album: 'High Energy',                         an: 1975 },
        { artist: 'James Cotton',          album: 'Taking Care of Business',             an: 1971 },
        { artist: 'Eddy Clearwater',       album: 'The Chief',                           an: 1980 },
        { artist: 'Jimmy Dawkins',         album: 'Fast Fingers',                        an: 1969 },
        { artist: 'Carey Bell',            album: 'Last Night',                          an: 1995 },
        { artist: 'Willie Dixon',          album: 'I Am the Blues',                      an: 1970 },
        { artist: 'Willie Dixon',          album: 'The Chess Box',                       an: 1988 },
        { artist: 'J.B. Lenoir',           album: 'Alabama Blues!',                      an: 1965 },
        { artist: 'Jimmy Witherspoon',     album: 'Evenin\' Blues',                      an: 1963 },
        { artist: 'Sunnyland Slim',        album: 'Slim\'s Got His Thing Together',      an: 1969 },
        { artist: 'Memphis Slim',          album: 'Memphis Slim at the Gate of Horn',    an: 1959 },
        { artist: 'Roosevelt Sykes',       album: 'The Honeydripper',                    an: 1961 },
        { artist: 'Big Maceo',             album: 'Chicago Breakdown',                   an: 1975 },
        { artist: 'Pinetop Perkins',       album: 'After Hours',                         an: 1988 },
        { artist: 'Homesick James',        album: 'Goin\' Back Home',                    an: 1971 },
        { artist: 'Floyd Jones',           album: 'Masters of Modern Blues',             an: 1966 },
        { artist: 'Johnny Young',          album: 'Chicago Blues',                       an: 1965 },
        { artist: 'Eddie Taylor',          album: 'I Feel So Bad',                       an: 1972 },
        { artist: 'Snooky Pryor',          album: 'Do It If You Wanna',                  an: 1987 },
        { artist: 'Andrew Brown',          album: 'Big Brown Blues',                     an: 1982 },
        { artist: 'Lazy Lester',           album: 'I\'m a Lover Not a Fighter',          an: 1994 },
        { artist: 'Slim Harpo',            album: 'I\'m a King Bee',                     an: 1989 },
    ]
};
