/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/blues/delta-blues.js
   50 albume esențiale de Delta Blues
═══════════════════════════════════════════════════════════════ */

window.deltaBluesData = {
    gen: 'blues',
    subgen: 'delta-blues',
    label: 'Delta Blues',
    albume: [
        { artist: 'Robert Johnson',        album: 'King of the Delta Blues Singers',     an: 1961 },
        { artist: 'Robert Johnson',        album: 'King of the Delta Blues Singers Vol. 2', an: 1970 },
        { artist: 'Muddy Waters',          album: 'At Newport 1960',                     an: 1960 },
        { artist: 'Muddy Waters',          album: 'Folk Singer',                         an: 1964 },
        { artist: 'Muddy Waters',          album: 'Hard Again',                          an: 1977 },
        { artist: 'Charley Patton',        album: 'Founder of the Delta Blues',          an: 1960 },
        { artist: 'Son House',             album: 'Father of Delta Blues',               an: 1965 },
        { artist: 'Son House',             album: 'The Legendary Son House',             an: 1992 },
        { artist: 'Skip James',            album: 'Today!',                              an: 1966 },
        { artist: 'Skip James',            album: 'Devil Got My Woman',                  an: 1968 },
        { artist: 'Blind Lemon Jefferson', album: 'King of the Country Blues',           an: 1985 },
        { artist: 'Mississippi John Hurt', album: 'Today!',                              an: 1966 },
        { artist: 'Mississippi John Hurt', album: 'The Immortal Mississippi John Hurt',  an: 1967 },
        { artist: 'Lightnin\' Hopkins',    album: 'Mojo Hand',                           an: 1962 },
        { artist: 'Lightnin\' Hopkins',    album: 'Texas Blues Man',                     an: 1968 },
        { artist: 'Howlin\' Wolf',         album: 'Moanin\' in the Moonshine',           an: 1959 },
        { artist: 'Howlin\' Wolf',         album: 'Howlin\' Wolf',                       an: 1962 },
        { artist: 'Howlin\' Wolf',         album: 'The London Howlin\' Wolf Sessions',   an: 1971 },
        { artist: 'John Lee Hooker',       album: 'The Country Blues of John Lee Hooker', an: 1959 },
        { artist: 'John Lee Hooker',       album: 'Burnin\'',                            an: 1962 },
        { artist: 'John Lee Hooker',       album: 'The Healer',                          an: 1989 },
        { artist: 'Big Bill Broonzy',      album: 'Big Bill\'s Blues',                   an: 1958 },
        { artist: 'Mississippi Fred McDowell', album: 'You Gotta Move',                  an: 1969 },
        { artist: 'Mississippi Fred McDowell', album: 'I Do Not Play No Rock \'n\' Roll', an: 1969 },
        { artist: 'Tampa Red',             album: 'Guitar Wizard',                       an: 1975 },
        { artist: 'Blind Willie McTell',   album: 'The Definitive Blind Willie McTell',  an: 1994 },
        { artist: 'Tommy Johnson',         album: 'Complete Recorded Works',             an: 1990 },
        { artist: 'Sleepy John Estes',     album: 'Brownsville Blues',                   an: 1962 },
        { artist: 'Bukka White',           album: 'Sky Songs',                           an: 1965 },
        { artist: 'Leadbelly',             album: 'Midnight Special',                    an: 1991 },
        { artist: 'Leadbelly',             album: 'Good Night Irene',                    an: 1953 },
        { artist: 'Bo Diddley',            album: 'Bo Diddley',                          an: 1958 },
        { artist: 'Little Walter',         album: 'His Best',                            an: 1997 },
        { artist: 'Sonny Boy Williamson',  album: 'Down and Out Blues',                  an: 1959 },
        { artist: 'Sonny Boy Williamson',  album: 'The Real Folk Blues',                 an: 1966 },
        { artist: 'Elmore James',          album: 'The Sky Is Crying',                   an: 1965 },
        { artist: 'Elmore James',          album: 'Shake Your Moneymaker',               an: 1961 },
        { artist: 'Jimmy Reed',            album: 'The Best of Jimmy Reed',              an: 1961 },
        { artist: 'Otis Rush',             album: 'Right Place Wrong Time',              an: 1976 },
        { artist: 'Magic Sam',             album: 'West Side Soul',                      an: 1968 },
        { artist: 'Luther Allison',        album: 'Love Me Mama',                        an: 1969 },
        { artist: 'Junior Wells',          album: 'Hoodoo Man Blues',                    an: 1965 },
        { artist: 'Buddy Guy',             album: 'A Man and the Blues',                 an: 1968 },
        { artist: 'Buddy Guy',             album: 'Damn Right I\'ve Got the Blues',      an: 1991 },
        { artist: 'J.B. Hutto',            album: 'Hawk Squat',                          an: 1968 },
        { artist: 'James Cotton',          album: 'Cut You Loose!',                      an: 1967 },
        { artist: 'Carey Bell',            album: 'Goin\' On',                           an: 1977 },
        { artist: 'Lowell Fulson',         album: 'Reconsider Baby',                     an: 1954 },
        { artist: 'Arthur Crudup',         album: 'That\'s All Right Mama',              an: 1994 },
        { artist: 'Robert Nighthawk',      album: 'Live on Maxwell Street',              an: 1980 },
    ]
};
