/* ═══════════════════════════════════════════════════════════════
   BIBLIOTECA MUZICALĂ — database/blues/electric-blues.js
   50 albume esențiale de Electric Blues
═══════════════════════════════════════════════════════════════ */

window.electricBluesData = {
    gen: 'blues',
    subgen: 'electric-blues',
    label: 'Electric Blues',
    albume: [
        { artist: 'B.B. King',             album: 'Live at the Regal',                   an: 1965 },
        { artist: 'B.B. King',             album: 'Completely Well',                     an: 1969 },
        { artist: 'B.B. King',             album: 'Live in Cook County Jail',            an: 1971 },
        { artist: 'B.B. King',             album: 'Riding with the King',                an: 2000 },
        { artist: 'Albert King',           album: 'Born Under a Bad Sign',               an: 1967 },
        { artist: 'Albert King',           album: 'Live Wire / Blues Power',             an: 1968 },
        { artist: 'Albert King',           album: 'I\'ll Play the Blues for You',        an: 1972 },
        { artist: 'Freddie King',          album: 'Let\'s Hide Away and Dance Away',     an: 1961 },
        { artist: 'Freddie King',          album: 'Getting Ready',                       an: 1971 },
        { artist: 'Stevie Ray Vaughan',    album: 'Texas Flood',                         an: 1983 },
        { artist: 'Stevie Ray Vaughan',    album: 'Couldn\'t Stand the Weather',         an: 1984 },
        { artist: 'Stevie Ray Vaughan',    album: 'Soul to Soul',                        an: 1985 },
        { artist: 'Stevie Ray Vaughan',    album: 'In Step',                             an: 1989 },
        { artist: 'Eric Clapton',          album: 'From the Cradle',                     an: 1994 },
        { artist: 'Eric Clapton',          album: 'Me and Mr. Johnson',                  an: 2004 },
        { artist: 'Eric Clapton',          album: 'Unplugged',                           an: 1992 },
        { artist: 'Gary Moore',            album: 'Still Got the Blues',                 an: 1990 },
        { artist: 'Gary Moore',            album: 'After Hours',                         an: 1992 },
        { artist: 'Johnny Winter',         album: 'Second Winter',                       an: 1969 },
        { artist: 'Johnny Winter',         album: 'Johnny Winter And',                   an: 1970 },
        { artist: 'Johnny Winter',         album: 'Nothin\' But the Blues',              an: 1977 },
        { artist: 'Albert Collins',        album: 'Ice Pickin\'',                        an: 1978 },
        { artist: 'Albert Collins',        album: 'Frostbite',                           an: 1980 },
        { artist: 'Albert Collins',        album: 'Showdown!',                           an: 1985 },
        { artist: 'Robert Cray',           album: 'Strong Persuader',                    an: 1986 },
        { artist: 'Robert Cray',           album: 'Don\'t Be Afraid of the Dark',        an: 1988 },
        { artist: 'Taj Mahal',             album: 'Taj Mahal',                           an: 1968 },
        { artist: 'Taj Mahal',             album: 'The Natch\'l Blues',                  an: 1968 },
        { artist: 'Paul Butterfield Blues Band', album: 'The Paul Butterfield Blues Band', an: 1965 },
        { artist: 'Paul Butterfield Blues Band', album: 'East-West',                     an: 1966 },
        { artist: 'Canned Heat',           album: 'Boogie with Canned Heat',             an: 1968 },
        { artist: 'Mike Bloomfield',       album: 'Super Session',                       an: 1968 },
        { artist: 'Rory Gallagher',        album: 'Blueprint',                           an: 1973 },
        { artist: 'Rory Gallagher',        album: 'Irish Tour \'74',                     an: 1974 },
        { artist: 'Rory Gallagher',        album: 'Tattoo',                              an: 1973 },
        { artist: 'Joe Bonamassa',         album: 'Blues Deluxe',                        an: 2003 },
        { artist: 'Joe Bonamassa',         album: 'Dust Bowl',                           an: 2011 },
        { artist: 'Joe Bonamassa',         album: 'Different Shades of Blue',            an: 2014 },
        { artist: 'Jonny Lang',            album: 'Lie to Me',                           an: 1997 },
        { artist: 'Kenny Wayne Shepherd',  album: 'Ledbetter Heights',                   an: 1995 },
        { artist: 'Robben Ford',           album: 'Talk to Your Daughter',               an: 1988 },
        { artist: 'Robben Ford',           album: 'Handful of Blues',                    an: 1995 },
        { artist: 'Susan Tedeschi',        album: 'Just Won\'t Burn',                    an: 1998 },
        { artist: 'Tedeschi Trucks Band',  album: 'Revelator',                           an: 2011 },
        { artist: 'Derek Trucks',          album: 'Soul Serenade',                       an: 1999 },
        { artist: 'Shemekia Copeland',     album: 'Turn the Heat Up',                    an: 1998 },
        { artist: 'Keb\' Mo\'',            album: 'Keb\' Mo\'',                          an: 1994 },
        { artist: 'John Mayall',           album: 'Blues Breakers with Eric Clapton',    an: 1966 },
        { artist: 'John Mayall',           album: 'A Hard Road',                         an: 1967 },
        { artist: 'Fleetwood Mac',         album: 'Peter Green\'s Fleetwood Mac',        an: 1968 },
    ]
};
